### ISSUE TITLE
Original train/dev/test splits for the ScLM model

### ISSUE THREAD

**Issue by clefourrier** [IBM/transformers-struct-guidance#3]
Hi!

I skimmed through the paper and code, and could not find the original train/dev/test set used for the ScLM model (based on BLLIP?), do you have them somewhere?

If they are not available, do you have similar train/dev/test splits I could use to test the model training?

**Comment by pqian11** [comment]
Hi, we used the BLLIP dataset prepared from previous work. The train/dev/test splits of the dataset (BLLIP-MD and BLLIP-LG) can be found [here](https://github.com/cpllab/syntactic-generalization). It might take a while to preprocess the dataset. If you can send me an email, we could explore alternative options for getting data to train the models.

**Comment by clefourrier** [comment]
OK, will do that!
